### ISSUE TITLE
A way to run all tests

### ISSUE THREAD

**Issue by myrgy** [danlamanna/helm-ctest#5]
It mught be greate to have a simple way to run all tests or some tests.
In addition keepenig last choise as a current selected item should be very convinient.

**Comment by danlamanna** [comment]
> It mught be greate to have a simple way to run all tests or some tests.

I'm not sure how this isn't offered by Helm itself. `M-a` will select all tests, and using the regular `C-SPC` syntax allows selecting arbitrary tests to run (see the gif on the README).

> In addition keepenig last choise as a current selected item should be very convinient.

I agree. I'm not sure if helm offers any way to do this sort of thing out of the box, or if it would have to be added. Perhaps `helm-resume` can work here.

**Comment by myrgy** [comment]
In my case it's a bit inconvenient - I have too long list of tests.
Btw, ctest allows to execute tests in parallel
What do you think about allowing to specify ctest binary - it will allow to add any required options via `.dir-locals.el`
Btw, about all tests at once - what about exporting one additional like with range 1,N and name `All tests`?

**Comment by danlamanna** [comment]
> In my case it's a bit inconvenient - I have too long list of tests.

The entire point of Helm is to efficiently select items from lists that are often quite long. This is why there are keybinds for selecting all, filtering by fuzzy matching, etc.

> What do you think about allowing to specify ctest binary - it will allow to add any required options via .dir-locals.el

Ideally there would be `defcustom`'s for the CTest binary and any CTest flags, and running helm CTest with a prefix argument would allow customizing the command.

> Btw, about all tests at once - what about exporting one additional like with range 1,N and name All tests?

This might make sense as a helm action or something, but certainly not as a completion candidate - again, that goes against the entire point of helm.

To be frank, I hardly use helm *or* ctest anymore - so it's unlikely I'll make any of these changes. I'll gladly accept PRs though.

**Comment by myrgy** [comment]
about all items - my fault, I was not aware about M-a. In that case items is not required.
Current version is enough for me, but as soon as I'll suffer from the lack if parallel execution I'll prepare a PR.
Thank you, @danlamanna !
