### ISSUE TITLE
enable fuzzy matching

### ISSUE THREAD

**Issue by myrgy** [danlamanna/helm-ctest#8]
Hi @danlamanna,
it might be great to enable fuzzy mathing, like helm-make does

```lisp
(defcustom helm-ctest-fuzzy-matching nil
  "When non-nil, enable fuzzy matching in helm ctest target(s) buffer."
:type 'boolean)
```

```lisp
  (interactive)
  (helm :sources (helm-build-sync-source "CTests"
                   :candidates (helm-ctest-candidates)
                  :fuzzy-match helm-ctest-fuzzy-matching
                   :action '(("run tests" . helm-ctest-action)))
:buffer "*helm ctest*"))
```

Thank you in advance!

**Comment by danlamanna** [comment]
Sorry for the late response @myrgy.

To be frank, I don't use `helm` *or* `ctest` much anymore - so I'm unlikely to do personal work on this. I'll gladly merge any PR that looks reasonable though.

**Comment by myrgy** [comment]
Looks like after some changes in helm it works fine now.
